openapi: 3.0.0
info:
  title: "LudoAPI"
  version: "0.0.1"
  contact:
    name: Team MonstersINC
    email: contact@example.com
    url: https://example.com/
paths:
  /ludo/game/new:
    get:
  /ludo/game/{gameId}/addplayer:
    post:
  /ludo/game/{gameId}/roll:
    get:
      description: Rolls the die and return what number it gave.
  /ludo/game/{gameId}/movepiece:
    get:
      description: Moves the piece